In [1]:
import sys
import os
project_dir = os.path.dirname(os.getcwd())
sys.path.append(project_dir) #notebooks can't look into source unless you append the parent project directory to the path
print(project_dir)

/home/ubuntu/courtney/usal_echo

In [2]:
import numpy as np
import pandas as pd

In [3]:
sys.path.append('../src')
from d00_utils.db_utils import *

/home/ubuntu/anaconda3/envs/usal_echo/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)

In [4]:
io_segmentation = dbReadWriteSegmentation()

In [13]:
evaluations = io_segmentation.get_table('evaluations')
print(evaluations.shape)
evaluations

(606, 11)

,evaluation_id,study_id,instance_id,file_name,frame,model_name,chamber,score_type,score_value,gt_view_name,pred_view_name
0,74,43763,779540,,51,,lv,iou,0.269530,a4c,a4c
1,75,43763,779540,,68,,lv,iou,0.242520,a4c,a4c
2,76,46919,841585,,46,,lv,iou,0.293943,a4c,a4c
3,77,46919,841585,,60,,lv,iou,0.263671,a4c,a4c
4,78,50521,921901,,51,,lv,iou,0.291718,a4c,a4c
5,79,50521,921901,,68,,lv,iou,0.252421,a4c,a4c
6,80,57515,1078635,,58,,lv,iou,0.291225,a4c,a4c
7,81,57515,1078635,,75,,lv,iou,0.274314,a4c,a4c
8,82,57770,1084663,,137,,lv,iou,0.274314,a2c,a4c
9,83,57770,1084663,,153,,lv,iou,0.274314,a2c,a4c
10,84,59792,1139169,,34,,lv,iou,0.274314,a2c,a4c
11,85,59792,1139169,,54,,lv,iou,0.274314,a2c,a4c
12,86,60906,1168238,,59,,lv,iou,0.252001,a4c,a4c
13,87,60906,1168238,,79,,lv,iou,0.290498,a4c,a4c
14,88,61989,1197478,,1,,lv,iou,0.215664,a4c,a4c
15,89,61989,1197478,,16,,lv,iou,0.273546,a4c,a4c
16,90,70250,1385486,,1,,lv,iou,0.156789,a4c,a4c
17,91,70250,1385486,,18,,lv,iou,0.172032,a4c,a4c
18,92,70927,1401364,,27,,lv,iou,0.172032,a2c,a4c
19,93,70927,1401364,,40,,lv,iou,0.172032,a2c,a4c
20,94,72618,1444546,,0,,lv,iou,0.278633,a4c,a4c
21,95,72618,1444546,,23,,lv,iou,0.279560,a4c,a4c
22,96,73922,1481908,,31,,lv,iou,0.279560,a2c,a4c
23,97,73922,1481908,,51,,lv,iou,0.279560,a2c,a4c
24,98,74054,1485803,,48,,lv,iou,0.730691,a4c,a4c
25,99,74054,1485803,,61,,lv,iou,0.485683,a4c,a4c
26,100,74226,1490854,,43,,lv,iou,0.485683,a2c,a4c
27,101,74226,1490854,,61,,lv,iou,0.485683,a2c,a4c
28,102,74472,1496711,,1,,lv,iou,0.648990,a4c,a4c
29,103,74472,1496711,,18,,lv,iou,0.630858,a4c,a4c
...,...,...,...,...,...,...,...,...,...,...,...
576,650,101071,2274669,,86,,lv,iou,0.243661,a4c,a4c
577,651,101071,2274669,,86,,la,iou,0.249399,a4c,a4c
578,652,101322,2281407,,1,,lv,iou,0.249399,a2c,a4c
579,653,101322,2281407,,25,,lv,iou,0.249399,a2c,a4c
580,654,101322,2281407,,25,,la,iou,0.249399,a2c,a4c
581,655,101530,2287740,,69,,la,iou,0.275182,a4c,a4c
582,656,101548,2288307,,24,,la,iou,0.705360,a4c,a4c
583,657,101565,2288607,,34,,lv,iou,0.274544,a4c,a4c
584,658,101565,2288607,,51,,lv,iou,0.271937,a4c,a4c
585,659,101565,2288607,,51,,la,iou,0.274886,a4c,a4c
586,660,101793,2294829,,108,,lv,iou,0.274886,a2c,a4c
587,661,101793,2294829,,125,,lv,iou,0.274886,a2c,a4c
588,662,101793,2294829,,125,,la,iou,0.274886,a2c,a4c
589,663,101843,2295974,,80,,lv,iou,0.261049,a4c,a4c
590,664,101843,2295974,,95,,lv,iou,0.274428,a4c,a4c
591,665,101843,2295974,,95,,la,iou,0.264110,a4c,a4c
592,666,102155,2305262,,42,,lv,iou,0.714488,a4c,a4c
593,667,102155,2305262,,56,,lv,iou,0.626214,a4c,a4c
594,668,102155,2305262,,56,,la,iou,0.835235,a4c,a4c
595,669,102218,2306896,,49,,lv,iou,0.227115,a4c,a4c
596,670,102218,2306896,,66,,lv,iou,0.260339,a4c,a4c
597,671,102218,2306896,,66,,la,iou,0.266423,a4c,a4c
598,672,102218,2306958,,50,,lv,iou,0.266423,a2c,a4c
599,673,102218,2306958,,64,,lv,iou,0.266423,a2c,a4c
600,674,102218,2306958,,64,,la,iou,0.266423,a2c,a4c
601,675,102242,2307604,,54,,la,iou,0.242743,a4c,a4c
602,676,102288,2309024,,2,,lv,iou,0.289336,a4c,a4c
603,677,102288,2309024,,20,,lv,iou,0.186791,a4c,a4c
604,678,102636,2317460,,70,,la,iou,0.516349,a4c,a4c
605,679,102742,2319962,,0,,lv,iou,0.820018,a4c,a4c

In [16]:
evaluations['pred_view_name'].value_counts()

a4c    606
Name: pred_view_name, dtype: int64

## Numbers of records in the evaluation table

In [9]:
print('{} records in the evaluation table'.format(evaluations.shape[0]))

#Count the number of instances where gt_view_name != pred_view_name
count = 0
evaluations['views dont match'] = 0
for i in evaluations.index:
    if evaluations.at[i, 'gt_view_name'] != evaluations.at[i, 'pred_view_name']:
        count +=1
        evaluations.at[i, 'views dont match'] = 1
print('{} record where the view does not match'.format(count))
print("checking column for record where the view does not match: {}".format(evaluations['views dont match'].sum()))

547 records in the evaluation table
231 record where the view does not match
checking column for record where the view does not match: 231

## Average IOU Scores for data subsets

In [12]:
#for views that do match, what is the average IOU
evaluations_matching_views = evaluations[evaluations['views dont match'] == 0]
print('Average IOU for tests where the views do match: {}'.format(evaluations_matching_views['score_value'].mean()))
evaluations_non_matching_views = evaluations[evaluations['views dont match'] == 1]
print('Average IOU for tests where the views dont match: {}'.format(evaluations_non_matching_views['score_value'].mean()))
print('')
#for subsets
evaluations_matching_views_a4c = evaluations_matching_views[evaluations_matching_views['gt_view_name'] == 'a4c']
print('Average IOU for a4c tests where the views do match: {}'.format(evaluations_matching_views_a4c['score_value'].mean()))
evaluations_matching_views_a2c = evaluations_matching_views[evaluations_matching_views['gt_view_name'] == 'a2c']
print('Average IOU for a2c tests where the views do match: {}'.format(evaluations_matching_views_a2c['score_value'].mean()))

Average IOU for tests where the views do match: 0.4031028120963518
Average IOU for tests where the views dont match: 0.4097675403781635

Average IOU for a4c tests where the views do match: 0.4031028120963518
Average IOU for a2c tests where the views do match: nan