In [1]:
%reload_ext autoreload
%autoreload 2

In [2]:
import sys
sys.path.append('../src')

In [3]:
folder = 'test_downsampleby5'

In [4]:
from d05_measurement.analyse_segments import calculate_measurements
df = calculate_measurements(folder)
print(df.shape)
df.head()

/home/ubuntu/anaconda3/envs/usal_echo/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)

(18, 13)
[]
[106.01080296093093, 104.04659970539346, 103.27344378415434]
ef: 0.033887996132051984
[90.78613560088569]
[]
[]
[67.56315215756715, 68.78198501856727, 69.3059088346159]
[70.4855297629678, 72.87115627893866]
[]
lavol: 1.9156755629460787
[104.93025624129191, 88.06453676318951, 104.55110994711882]
[]
[]
ef: 0.9156870421437185
[73.50789434582984]
[]
[]
[]
[]
[]
[]
Seconds: 161.6765580177307
Seconds/File: 4.041913950443268
skips: 0
(72, 7)

,study_id,instance_id,file_name,date_run,measurement_name,measurement_unit,measurement_value
0,74920,1507806,a_74920_1FZH4296,2019-08-15 12:57:25.436586,VTD(MDD-ps4),mL,NaN
1,74920,1507806,a_74920_1FZH4296,2019-08-15 12:57:25.436586,VTS(MDD-ps4),mL,NaN
2,74920,1507806,a_74920_1FZH4296,2019-08-15 12:57:25.436586,FE(MDD-ps4),%,NaN
3,74920,1507806,a_74920_1FZH4296,2019-08-15 12:57:25.436586,recommendation,,greyzone
4,74958,1508983,a_74958_1GG0EP57,2019-08-15 12:57:25.436586,VTD(MDD-ps4),mL,105.618

In [5]:
import numpy as np
import pandas as pd
df[df['measurement_value'].isnull()]

,study_id,instance_id,file_name,date_run,measurement_name,measurement_unit,measurement_value
0,74920,1507806,a_74920_1FZH4296,2019-08-15 12:57:25.436586,VTD(MDD-ps4),mL,NaN
1,74920,1507806,a_74920_1FZH4296,2019-08-15 12:57:25.436586,VTS(MDD-ps4),mL,NaN
2,74920,1507806,a_74920_1FZH4296,2019-08-15 12:57:25.436586,FE(MDD-ps4),%,NaN
10,89909,1963141,a_89909_E5JHWH6K,2019-08-15 12:57:25.436586,FE(MDD-ps4),%,NaN
12,96624,2148595,a_96624_41PFB864,2019-08-15 12:57:25.436586,VTD(MDD-ps4),mL,NaN
13,96624,2148595,a_96624_41PFB864,2019-08-15 12:57:25.436586,VTS(MDD-ps4),mL,NaN
14,96624,2148595,a_96624_41PFB864,2019-08-15 12:57:25.436586,FE(MDD-ps4),%,NaN
16,103898,2355254,a_103898_ABQ7JVTK,2019-08-15 12:57:25.436586,VTD(MDD-ps4),mL,NaN
17,103898,2355254,a_103898_ABQ7JVTK,2019-08-15 12:57:25.436586,VTS(MDD-ps4),mL,NaN
18,103898,2355254,a_103898_ABQ7JVTK,2019-08-15 12:57:25.436586,FE(MDD-ps4),%,NaN
28,114188,2645647,a_114188_41920UKZ,2019-08-15 12:57:25.436586,VTD(MDD-ps4),mL,NaN
29,114188,2645647,a_114188_41920UKZ,2019-08-15 12:57:25.436586,VTS(MDD-ps4),mL,NaN
30,114188,2645647,a_114188_41920UKZ,2019-08-15 12:57:25.436586,FE(MDD-ps4),%,NaN
36,123558,2913510,a_123558_CSE8O0JK,2019-08-15 12:57:25.436586,VTD(MDD-ps4),mL,NaN
37,123558,2913510,a_123558_CSE8O0JK,2019-08-15 12:57:25.436586,VTS(MDD-ps4),mL,NaN
38,123558,2913510,a_123558_CSE8O0JK,2019-08-15 12:57:25.436586,FE(MDD-ps4),%,NaN
40,86137,1853667,a_86137_AHP1E39X,2019-08-15 12:57:25.436586,VTD(MDD-ps4),mL,NaN
41,86137,1853667,a_86137_AHP1E39X,2019-08-15 12:57:25.436586,VTS(MDD-ps4),mL,NaN
42,86137,1853667,a_86137_AHP1E39X,2019-08-15 12:57:25.436586,FE(MDD-ps4),%,NaN
46,91758,2013366,a_91758_FHS00AQO,2019-08-15 12:57:25.436586,FE(MDD-ps4),%,NaN
48,97220,2165100,a_97220_46RCF9AI,2019-08-15 12:57:25.436586,VTD(MDD-ps4),mL,NaN
49,97220,2165100,a_97220_46RCF9AI,2019-08-15 12:57:25.436586,VTS(MDD-ps4),mL,NaN
50,97220,2165100,a_97220_46RCF9AI,2019-08-15 12:57:25.436586,FE(MDD-ps4),%,NaN
52,99187,2221186,a_99187_6HG7QN19,2019-08-15 12:57:25.436586,VTD(MDD-ps4),mL,NaN
53,99187,2221186,a_99187_6HG7QN19,2019-08-15 12:57:25.436586,VTS(MDD-ps4),mL,NaN
54,99187,2221186,a_99187_6HG7QN19,2019-08-15 12:57:25.436586,FE(MDD-ps4),%,NaN
56,116357,2713002,a_116357_6EP5IGNU,2019-08-15 12:57:25.436586,VTD(MDD-ps4),mL,NaN
57,116357,2713002,a_116357_6EP5IGNU,2019-08-15 12:57:25.436586,VTS(MDD-ps4),mL,NaN
58,116357,2713002,a_116357_6EP5IGNU,2019-08-15 12:57:25.436586,FE(MDD-ps4),%,NaN
60,121253,2854040,a_121253_AE12AMWX,2019-08-15 12:57:25.436586,VTD(MDD-ps4),mL,NaN
61,121253,2854040,a_121253_AE12AMWX,2019-08-15 12:57:25.436586,VTS(MDD-ps4),mL,NaN
62,121253,2854040,a_121253_AE12AMWX,2019-08-15 12:57:25.436586,FE(MDD-ps4),%,NaN
64,126172,2987140,a_126172_EBZCZ8AT,2019-08-15 12:57:25.436586,VTD(MDD-ps4),mL,NaN
65,126172,2987140,a_126172_EBZCZ8AT,2019-08-15 12:57:25.436586,VTS(MDD-ps4),mL,NaN
66,126172,2987140,a_126172_EBZCZ8AT,2019-08-15 12:57:25.436586,FE(MDD-ps4),%,NaN
68,126442,2994496,a_126442_EEQL4LRY,2019-08-15 12:57:25.436586,VTD(MDD-ps4),mL,NaN
69,126442,2994496,a_126442_EEQL4LRY,2019-08-15 12:57:25.436586,VTS(MDD-ps4),mL,NaN
70,126442,2994496,a_126442_EEQL4LRY,2019-08-15 12:57:25.436586,FE(MDD-ps4),%,NaN