In [1]:
import sys
import os
project_dir = os.path.dirname(os.getcwd())
sys.path.append(project_dir) #notebooks can't look into source unless you append the parent project directory to the path
print(project_dir)

/home/ubuntu/courtney/usal_echo

In [2]:
import sqlalchemy
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
sys.path.append('../src')
from d00_utils.db_utils import *

/home/ubuntu/anaconda3/envs/usal_echo/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)

In [4]:
io_class = dbReadWriteClassification()
io_class.list_tables()

['probabilities_frames', 'test1000_for_m1', 'probabilities_frames_test', 'test_probabilities_instances', 'test_probabilities_frames', 'evaluations', 'ground_truths', 'probabilities_instances', 'test_predictions', 'predictions', 'test1000_for_m2_m3', 'evaluation']

In [6]:
predictions = io_class.get_table('test_predictions')
predictions.head(20)

,study_id,file_name,model_name,date_run,img_dir,view23_pred,view4_dev,view4_seg,test_prediction_id
0,40662,a_40662_BJCI4YWP,view_23_e5_class_11-Mar-2018,2019-08-14 17:55:48.640661,train_split100_downsampleby20,plax_plax,plax,plax,1
1,41874,a_41874_D4RS7VJH,view_23_e5_class_11-Mar-2018,2019-08-14 17:55:48.640661,train_split100_downsampleby20,other,other,other,2
2,45373,a_45373_5644FNM4,view_23_e5_class_11-Mar-2018,2019-08-14 17:55:48.640661,train_split100_downsampleby20,plax_plax,plax,plax,3
3,46044,a_46044_6GIHF62G,view_23_e5_class_11-Mar-2018,2019-08-14 17:55:48.640661,train_split100_downsampleby20,other,other,other,4
4,46663,a_46663_6RZXN68Y,view_23_e5_class_11-Mar-2018,2019-08-14 17:55:48.640661,train_split100_downsampleby20,plax_plax,plax,plax,5
5,49032,a_49032_BSJFL13M,view_23_e5_class_11-Mar-2018,2019-08-14 17:55:48.640661,train_split100_downsampleby20,a4c_laocc,a4c,other,6
6,50835,a_50835_FBSIXKAW,view_23_e5_class_11-Mar-2018,2019-08-14 17:55:48.640661,train_split100_downsampleby20,other,other,other,7
7,51333,a_51333_FKIQGBRT,view_23_e5_class_11-Mar-2018,2019-08-14 17:55:48.640661,train_split100_downsampleby20,a4c_laocc,a4c,other,8
8,52026,a_52026_1JNGHNU7,view_23_e5_class_11-Mar-2018,2019-08-14 17:55:48.640661,train_split100_downsampleby20,plax_plax,plax,plax,9
9,54230,a_54230_57HWV1A2,view_23_e5_class_11-Mar-2018,2019-08-14 17:55:48.640661,train_split100_downsampleby20,plax_plax,plax,plax,10
10,54835,a_54835_6G23ZBI2,view_23_e5_class_11-Mar-2018,2019-08-14 17:55:48.640661,train_split100_downsampleby20,other,other,other,11
11,56223,a_56223_7WVZWBCT,view_23_e5_class_11-Mar-2018,2019-08-14 17:55:48.640661,train_split100_downsampleby20,a4c,a4c,a4c,12
12,56563,a_56563_8Z0O4KF8,view_23_e5_class_11-Mar-2018,2019-08-14 17:55:48.640661,train_split100_downsampleby20,plax_plax,plax,plax,13
13,56761,a_56761_942L0FFJ,view_23_e5_class_11-Mar-2018,2019-08-14 17:55:48.640661,train_split100_downsampleby20,a4c,a4c,a4c,14
14,56920,a_56920_97ACN5GB,view_23_e5_class_11-Mar-2018,2019-08-14 17:55:48.640661,train_split100_downsampleby20,other,other,other,15
15,57105,a_57105_9AYNSRFC,view_23_e5_class_11-Mar-2018,2019-08-14 17:55:48.640661,train_split100_downsampleby20,plax_plax,plax,plax,16
16,57164,a_57164_9BVQH3VF,view_23_e5_class_11-Mar-2018,2019-08-14 17:55:48.640661,train_split100_downsampleby20,other,other,other,17
17,57410,a_57410_ACMSHB22,view_23_e5_class_11-Mar-2018,2019-08-14 17:55:48.640661,train_split100_downsampleby20,plax_plax,plax,plax,18
18,57417,a_57417_AD3BM77K,view_23_e5_class_11-Mar-2018,2019-08-14 17:55:48.640661,train_split100_downsampleby20,a4c,a4c,a4c,19
19,57433,a_57433_AD3BV9E9,view_23_e5_class_11-Mar-2018,2019-08-14 17:55:48.640661,train_split100_downsampleby20,a2c_laocc,a2c,other,20

In [ ]:
io_segmentation = dbReadWriteSegmentation()

In [ ]:
evaluations = io_segmentation.get_table('evaluations')
evaluations.shape

In [ ]:
recent_evals = evaluations.tail(1157)
recent_evals.head()

In [ ]:
print('Average IOU score: {}, based on {} records'.format(recent_evals['score_value'].mean(), recent_evals.shape[0]))

In [ ]:
recent_evals_nonzero = recent_evals[recent_evals['score_value'] != 0]
recent_evals_nonzero.shape
print('Average IOU score (excluding zeros): {}, based on {} records'.format(recent_evals_nonzero['score_value'].mean(), recent_evals_nonzero.shape[0]))

In [ ]:
eval_a4c = recent_evals_nonzero[recent_evals_nonzero['gt_view_name'] == 'A4C']
eval_a4c.shape
print('Average IOU score for A4C (excluding zeros): {}, based on {} records'.format(eval_a4c['score_value'].mean(), eval_a4c.shape[0]))

In [ ]:
eval_a2c = recent_evals_nonzero[recent_evals_nonzero['gt_view_name'] == 'A2C']
eval_a2c.shape
print('Average IOU score for A2C (excluding zeros): {}, based on {} records'.format(eval_a2c['score_value'].mean(), eval_a2c.shape[0]))

In [ ]:
eval_lv = recent_evals_nonzero[recent_evals_nonzero['chamber'] == 'lv']
print('Average IOU score for LV (excluding zeros): {}, based on {} records'.format(eval_lv['score_value'].mean(), eval_lv.shape[0]))

In [ ]:
eval_la = recent_evals_nonzero[recent_evals_nonzero['chamber'] == 'la']
print('Average IOU score for LA (excluding zeros): {}, based on {} records'.format(eval_la['score_value'].mean(), eval_la.shape[0]))